# This is a config for E2B sandbox template.
# You can use template ID (542h7q6hpnbva31rz174) or template name (nova-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nova-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("nova-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nova-nextjs-test')

team_id = "aad3bcef-0f1f-4907-9119-a309f91bd07e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nova-nextjs-test"
template_id = "542h7q6hpnbva31rz174"
